"""
RAG pipeline API endpoints.
All endpoints require X-Internal-Secret header.

Accepted file types: .txt, .md
Original file is stored in R2 at rag-notes/{note_id}.{ext}.
Text is also passed through the pipeline (chunk → refine → embed → Pinecone).
"""

from __future__ import annotations

import asyncio
import functools
import logging
import uuid
from datetime import datetime, UTC

from fastapi import APIRouter, Depends, File, Form, Header, HTTPException, UploadFile, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.database import get_db
from app.models.rag_note import RagNote, RagNoteStatus
from app.r2_client import delete_object, upload_bytes
from app.rag.embedder import delete_note_vectors
from app.rag.pipeline import run_pipeline
from app.rag.schemas import NoteStatus
from app.redis_client import get_json
from app.subject_structure.loader import get_structure

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/rag", tags=["rag"])

_ALLOWED_EXTENSIONS = (".txt", ".md")


def require_internal_secret(x_internal_secret: str = Header(...)) -> None:
    if x_internal_secret != settings.MAIN_BACKEND_INTERNAL_SECRET:
        raise HTTPException(status_code=403, detail="Forbidden")


@router.post("/upload-note", status_code=status.HTTP_202_ACCEPTED)
async def upload_note(
    subject: str = Form(...),
    chapter: str = Form(...),
    display_name: str = Form(...),
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
    _: None = Depends(require_internal_secret),
):
    """
    Accept a .txt or .md RAG note file.
    - note_id is generated by the system (UUID4) — admin does not provide it
    - Stores the original file in R2 at rag-notes/{note_id}.{ext}
    - Creates a RagNote DB record
    - Starts the pipeline (chunk → refine → embed → Pinecone) in background
    Returns immediately with status=queued and the generated note_id.
    """
    filename = (file.filename or "upload").lower()
    if not any(filename.endswith(ext) for ext in _ALLOWED_EXTENSIONS):
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type. Allowed: {', '.join(_ALLOWED_EXTENSIONS)}",
        )

    file_bytes = await file.read()
    if len(file_bytes) == 0:
        raise HTTPException(status_code=400, detail="Uploaded file is empty")

    note_id = str(uuid.uuid4())

    # Upload original file to R2
    file_ext = ".md" if filename.endswith(".md") else ".txt"
    r2_key = f"rag-notes/{note_id}{file_ext}"
    content_type = "text/markdown" if file_ext == ".md" else "text/plain"

    loop = asyncio.get_event_loop()
    try:
        r2_url = await loop.run_in_executor(
            None, functools.partial(upload_bytes, r2_key, file_bytes, content_type)
        )
    except Exception as exc:
        logger.error("R2 upload failed for note_id=%s: %s", note_id, exc)
        raise HTTPException(status_code=500, detail=f"File storage failed: {exc}")

    file_content = file_bytes.decode("utf-8", errors="replace")

    note = RagNote(
        note_id=note_id,
        subject=subject,
        chapter=chapter,
        display_name=display_name,
        status=RagNoteStatus.queued,
        r2_key=r2_key,
        r2_url=r2_url,
        created_at=datetime.now(UTC),
    )
    db.add(note)
    await db.commit()
    await db.refresh(note)

    asyncio.create_task(run_pipeline(note_id, subject, chapter, file_content))

    logger.warning("RAG note queued: note_id=%s subject=%s chapter=%s", note_id, subject, chapter)
    return {"note_id": note_id, "status": "queued", "row_id": note.id, "r2_key": r2_key}


@router.get("/status/{note_id}", response_model=NoteStatus)
async def get_note_status(
    note_id: str,
    db: AsyncSession = Depends(get_db),
    _: None = Depends(require_internal_secret),
):
    """Get pipeline progress. Reads from Redis first, falls back to DB."""
    note_id = note_id.strip()
    redis_data = await get_json(f"rag:job:{note_id}")
    result = await db.execute(select(RagNote).where(RagNote.note_id == note_id))
    note = result.scalar_one_or_none()
    if not note:
        raise HTTPException(status_code=404, detail="Note not found")

    if redis_data:
        return NoteStatus(
            note_id=note_id,
            status=redis_data.get("status", "unknown"),
            stage=redis_data.get("stage", "unknown"),
            progress_pct=redis_data.get("progress_pct", 0),
            message=redis_data.get("message", ""),
            total_chunks=note.total_chunks,
            error_message=note.error_message,
        )

    return NoteStatus(
        note_id=note_id,
        status=note.status,
        stage=note.status,
        progress_pct=100 if note.status == "completed" else 0,
        message="",
        total_chunks=note.total_chunks,
        error_message=note.error_message,
    )


@router.get("/notes")
async def list_notes(
    db: AsyncSession = Depends(get_db),
    _: None = Depends(require_internal_secret),
):
    """List all RAG notes ordered by created_at desc."""
    result = await db.execute(select(RagNote).order_by(RagNote.created_at.desc()))
    notes = result.scalars().all()
    return [
        {
            "note_id": n.note_id,
            "subject": n.subject,
            "chapter": n.chapter,
            "display_name": n.display_name,
            "status": n.status,
            "total_chunks": n.total_chunks,
            "error_message": n.error_message,
            "r2_key": n.r2_key,
            "r2_url": n.r2_url,
            "created_at": n.created_at,
            "completed_at": n.completed_at,
        }
        for n in notes
    ]


@router.delete("/notes/{note_id}")
async def delete_note(
    note_id: str,
    db: AsyncSession = Depends(get_db),
    _: None = Depends(require_internal_secret),
):
    """Delete a note: removes the R2 file, all Pinecone vectors, and the DB record."""
    note_id = note_id.strip()
    result = await db.execute(select(RagNote).where(RagNote.note_id == note_id))
    note = result.scalar_one_or_none()
    if not note:
        raise HTTPException(status_code=404, detail="Note not found")

    # Delete from R2
    if note.r2_key:
        loop = asyncio.get_event_loop()
        try:
            await loop.run_in_executor(None, functools.partial(delete_object, note.r2_key))
        except Exception as exc:
            logger.warning("R2 delete failed for key=%s: %s (continuing)", note.r2_key, exc)

    # Delete from Pinecone
    await delete_note_vectors(note_id)

    await db.delete(note)
    await db.commit()

    return {"deleted": True, "note_id": note_id}


@router.get("/structure/{subject}")
async def get_subject_structure(
    subject: str,
    _: None = Depends(require_internal_secret),
):
    """Return the full subject structure JSON for the given subject."""
    try:
        return get_structure(subject)
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail=f"Structure for subject '{subject}' not found")
